# Generated by Django 5.2 on 2025-04-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Initial Price')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Price')),
                ('price_update_frequency', models.CharField(choices=[('1M', 'Every 1 month'), ('3M', 'Every 3 months'), ('6M', 'Every 6 months')], default='1M', max_length=2, verbose_name='Price Update Frequency')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='models.apartment', verbose_name='Apartment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='models.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
    ]
