# Generated by Django 5.2 on 2025-04-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='initial_price',
        ),
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('IPC', 'Consumer Price Index'), ('UF', 'Unit of Account (UF)')], max_length=10, verbose_name='Indicator Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Economic Indicator',
                'verbose_name_plural': 'Economic Indicators',
                'ordering': ['-date'],
                'unique_together': {('indicator_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('reason', models.CharField(blank=True, help_text='Reason for the price change (e.g., IPC adjustment, contract renegotiation).', max_length=255, null=True, verbose_name='Reason')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='models.contract', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Historical Price',
                'verbose_name_plural': 'Historical Prices',
                'ordering': ['-date'],
            },
        ),
    ]
