# Generated by Django 5.2 on 2025-04-03 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_remove_contract_current_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='economicindicator',
            options={'ordering': ['-date'], 'verbose_name': 'Indicador económico', 'verbose_name_plural': 'Indicadores Económicos'},
        ),
        migrations.AlterModelOptions(
            name='historicalprice',
            options={'ordering': ['-date'], 'verbose_name': 'Precio histórico', 'verbose_name_plural': 'Precios históricos'},
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='client',
            name='rut',
            field=models.CharField(null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='contract',
            name='next_price_update',
            field=models.DateField(null=True, verbose_name='Próximo ajuste'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email Inquilino'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre Inquilino'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Teléfono Inquilino'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='models.apartment', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='models.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Término'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_update_frequency',
            field=models.CharField(choices=[('1M', 'Cada 1 mes'), ('3M', 'Cada 3 meses'), ('6M', 'Cada 6 meses')], default='1M', max_length=2, verbose_name='Frecuencia de actualización de precio'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='economicindicator',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='economicindicator',
            name='indicator_type',
            field=models.CharField(choices=[('IPC', 'Índice Precio del Consumidor'), ('UF', 'Unidad de Fomento')], max_length=10, verbose_name='Tipo indicador'),
        ),
        migrations.AlterField(
            model_name='economicindicator',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='models.contract', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='reason',
            field=models.CharField(blank=True, help_text='Motivo del cambio de precio (IPC, acuerdo mutuo, etc).', max_length=255, null=True, verbose_name='Motivo'),
        ),
    ]
