# Generated by Django 5.2 on 2025-04-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_apartment_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price_update_frequency',
            field=models.CharField(choices=[('1M', 'Cada 1 mes'), ('3M', 'Cada 3 meses'), ('6M', 'Cada 6 meses'), ('12M', 'Cada 12 meses')], default='1M', max_length=7, verbose_name='Frecuencia de actualización de precio'),
        ),
    ]
