# Generated by Django 5.2 on 2025-04-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_contract_price_update_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Teléfono')),
                ('rut', models.CharField(null=True, unique=True, verbose_name='RUT')),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
            },
        ),
        migrations.RemoveField(
            model_name='contract',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenant_email',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenant_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenant_phone',
        ),
        migrations.AddField(
            model_name='contract',
            name='clients',
            field=models.ManyToManyField(related_name='contracts', to='models.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenants',
            field=models.ManyToManyField(related_name='contracts', to='models.tenant', verbose_name='Inquilinos'),
        ),
    ]
