# Generated by Django 5.2 on 2025-04-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_tenant_remove_contract_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='commune',
            field=models.CharField(null=True, verbose_name='Comuna'),
        ),
    ]
