# Generated by Django 5.2 on 2025-04-10 09:05

import django.db.models.deletion
import phonenumber_field.modelfields
import validations.rut
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_apartment_commune'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Teléfono')),
                ('rut', models.CharField(max_length=10, null=True, unique=True, validators=[validations.rut.RutValidator.validator], verbose_name='RUT')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.RemoveField(
            model_name='contract',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenants',
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apartments', to='models.person', verbose_name='Propietario'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
