# Generated by Django 5.2 on 2025-04-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_person_remove_contract_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tenants',
            field=models.ManyToManyField(related_name='contracts', to='models.person', verbose_name='Arrendatarios'),
        ),
    ]
