# Generated by Django 5.2 on 2025-04-11 08:10

import validations.rut
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_contract_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rut',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[validations.rut.RutValidator.validator], verbose_name='RUT'),
        ),
    ]
