# Generated by Django 5.2 on 2025-04-19 07:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_comment_options_alter_comment_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión'),
        ),
    ]
